#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$DIR"

dotnet build dataprotection-repro.sln

test_string="This is a test message"
echo "*** Protecting with .NET 6.0 ... ***"
protected_string="$(dotnet run --project ./ReproApp --framework net6.0 -- protect "$test_string")"
echo "Protected string: $protected_string"
echo "Unprotecting with .NET 6.0 ..."
dotnet run --project ./ReproApp --framework net6.0 -- unprotect "$protected_string"
echo "Unprotecting with .NET 7.0 ..."
dotnet run --project ./ReproApp --framework net7.0 -- unprotect "$protected_string"

echo "*** Protecting with .NET 7.0 ... ***"
protected_string="$(dotnet run --project ./ReproApp --framework net7.0 -- protect "$test_string")"
echo "Protected string: $protected_string"
echo "Unprotecting with .NET 6.0 ..."
dotnet run --project ./ReproApp --framework net6.0 -- unprotect "$protected_string"
echo "Unprotecting with .NET 7.0 ..."
dotnet run --project ./ReproApp --framework net7.0 -- unprotect "$protected_string"